### ISSUE TITLE
Bug: negative string size

### ISSUE THREAD

**Issue by JoshCheek** [JoshCheek/seeing_is_believing#117]
```ruby
/(?<p>.(?<c>\g<p>?).)/.match("aabb").inspect  # ~> ArgumentError: negative string size (or size too big)

# ~> ArgumentError
# ~> negative string size (or size too big)
# ~>
# ~> /var/folders/yj/23xw_th91pl6xkdnyc733r01t48gqj/T/seeing_is_believing_temp_dir20170629-23924-ex8o0i/program.rb:1:in `inspect'
# ~> /var/folders/yj/23xw_th91pl6xkdnyc733r01t48gqj/T/seeing_is_believing_temp_dir20170629-23924-ex8o0i/program.rb:1:in `<main>'
```

**Comment by JoshCheek** [comment]
This is a bug in Ruby, not SiB, it's fixed in 2.4.1
![screen shot 2017-09-11 at 1 57 34 pm](https://user-images.githubusercontent.com/77495/30291672-3ac808e4-96f9-11e7-91ed-629438ac1037.png)
