### ISSUE TITLE
Clobbering issue

### ISSUE THREAD

**Issue by brandonpittman** [JoshCheek/seeing_is_believing#68]
No matter what I run it on, seeing_is_believing outputs this kind of error:

```ruby
program-without-annotations:1:1: error: cannot insert "$SiB.record_result(1, ("
program-without-annotations:1: foo = 1 # =>
program-without-annotations:1:             
program-without-annotations:1:1: note: clobbered by: insert "begin; $SiB.number_of_captures = Float::INFINITY; "
program-without-annotations:1: foo = 1 # =>
program-without-annotations:1:             
Parser::ClobberingError
Parser::Source::Rewriter detected clobbering

/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/parser-2.3.0.4/lib/parser/source/rewriter.rb:387:in `raise_clobber_error'
/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/parser-2.3.0.4/lib/parser/source/rewriter.rb:209:in `append'
/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/parser-2.3.0.4/lib/parser/source/rewriter.rb:64:in `insert_before'
/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/wrap_expressions.rb:36:in `block in call'
/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/wrap_expressions.rb:35:in `each'
/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/wrap_expressions.rb:35:in `call'
/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/wrap_expressions.rb:11:in `call'
/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing.rb:52:in `program_that_will_record_expressions'
/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing.rb:34:in `call'
/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing.rb:15:in `call'
/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary/add_annotations.rb:29:in `initialize'
/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:154:in `new'
/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:154:in `annotator'
/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:114:in `evaluate_program'
/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:45:in `call'
/Users/brandonpittman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/bin/seeing_is_believing:6:in `<top (required)>'
/Users/brandonpittman/.rbenv/versions/2.3.0/bin/seeing_is_believing:22:in `load'
/Users/brandonpittman/.rbenv/versions/2.3.0/bin/seeing_is_believing:22:in `<main>'
```

Happens from Vim or using the CLI.

**Comment by JoshCheek** [comment]
Hi, thanks for reporting! Can you try it against version 3.0.0.beta.6?

**Comment by JoshCheek** [comment]
(IIRC, you will need to uninstall 2.2.0)

**Comment by brandonpittman** [comment]
That fixed it. Thanks.

**Comment by JoshCheek** [comment]
Np, I should release that as a not-beta >.<
