### ISSUE TITLE
Clobbering issue

### ISSUE THREAD

**Issue by matthewswan** [JoshCheek/seeing_is_believing#72]
SiB works on personal machine, but doesn't cooperate on work machine. I am continuously getting this error when attempting to SiB a simple method:

```
def to_integer(string)
  string.to_i
end
```

Error message:

```
program-without-annotations:6:17: error: cannot insert ";rescue Exception;lambda {line_number = $!.backtrace.grep(/\#{__FILE__}/).first[/:\\d+/][1..-1].to_i;$SiB.record_exception line_number, $!;$SiB.exitstatus = 1;$SiB.exitstatus = $!.status if $!.kind_of? SystemExit;}.call;end"
program-without-annotations:6: to_integer('75')
program-without-annotations:6:                 
program-without-annotations:6:17: note: clobbered by: insert "))"
program-without-annotations:6: to_integer('75')
program-without-annotations:6:                 
Parser::ClobberingError
Parser::Source::Rewriter detected clobbering

/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/gems/parser-2.3.1.2/lib/parser/source/rewriter.rb:432:in `raise_clobber_error'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/gems/parser-2.3.1.2/lib/parser/source/rewriter.rb:254:in `append'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/gems/parser-2.3.1.2/lib/parser/source/rewriter.rb:101:in `insert_after'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/wrap_expressions.rb:44:in `call'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/wrap_expressions.rb:11:in `call'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing.rb:52:in `program_that_will_record_expressions'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing.rb:34:in `call'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing.rb:15:in `call'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary/add_annotations.rb:29:in `initialize'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:154:in `new'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:154:in `annotator'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:114:in `evaluate_program'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:45:in `call'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/gems/seeing_is_believing-2.2.0/bin/seeing_is_believing:6:in `<top (required)>'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/bin/seeing_is_believing:23:in `load'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/bin/seeing_is_believing:23:in `<main>'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/bin/ruby_executable_hooks:15:in `eval'
/Users/matthewswan/.rvm/gems/ruby-2.2.4@giftcards/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by JoshCheek** [comment]
Try uninstalling sib and parser and reinstalling the latest beta version.
I'll just release the beta as v3.0, it's dumb to keep waiting. (It's
ultimately a version incompatibility issue between SiB and Parser)

--Josh

**Comment by matthewswan** [comment]
Thanks! The beta is working great thus far!!
